#tells Connexion what version of the Swagger API is being used
swagger: "2.0"
info:
  description: This is swagger file that goes with our server code to trigger events
  version: "1.0.0"
  title: Event-trigger

consumes:
  - application/json
produces:
  - application/json

#"/api" defines the root of the API, kind of like a namespace the REST API will come from.
basePath: /api

# Paths supported by the server application
paths:
  /events:  #defines one path of your URL endpoint.
    
    post:
      operationId: events.create
      tags:
        - Events
      summary: Create an event and add it to the events list
      description: Create a new event in the events list
      parameters:
        - name: event
          in: body
          description: Event to create
          required: True
          schema:
            type: object
            properties:
              eventtype:
                type: string
                description: type of event to be created
              uuid:
                type: string
                description: uuid of event to be created
      responses:
        201:
          description: Successfully created event in list


 

    